import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { headers } from 'next/headers';
import Navbar from "./components/navbar/Navbar";
import { generateQrCode } from "../utils/utils";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

generateQrCode()


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  const headerList = await headers(); // headers() को पहले resolve करो
  const userAgent = headerList.get("user-agent") || "";
  const isMobile = /android|iphone|ipad/i.test(userAgent);

  return (
    <html lang="en">
      {/* <SocketProvider> */}
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Navbar isMobile={isMobile} />

        {children}
      </body>
      {/* </SocketProvider> */}
    </html>
  );
}
